name: Build and Push KM3 images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image names and tags
        run: |
          echo "BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/km3base" >> $GITHUB_ENV
          echo "TEST_IMAGE=ghcr.io/${{ github.repository_owner }}/km3test" >> $GITHUB_ENV
          echo "BASE_TAG=1.0" >> $GITHUB_ENV
          echo "TEST_TAG=1.1" >> $GITHUB_ENV

      # ----------- BUILD km3base -----------
      - name: Build km3base
        run: |
          docker build \
            -t $BASE_IMAGE:$BASE_TAG \
            ./km3base

      - name: Push km3base
        run: |
          docker push $BASE_IMAGE:$BASE_TAG

      # ----------- BUILD km3test -----------
      - name: Build km3test
        run: |
          docker build \
            -t $TEST_IMAGE:$TEST_TAG \
            ./km3test

      - name: Push km3test
        run: |
